variables:
  UPSTREAM_WORKSPACE: ".upstream_workspace.yml"
  DEB_BUILD: "false" # since we have non-released upstream deps
  CATKIN_LINT_ARGS: "--ignore unknown_package"

.build_matrix:
  parallel:
    matrix:
      - ROS_DISTRO: noetic
        CI_IMAGE: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_ros

include:
  - project: 'continuous_integration/ci_scripts'
    ref: master
    file: '/gitlab-ci-yml/catkin_pipeline.yml'
