name: Noetic

on: [push, pull_request]


jobs:
  industrial_ci:
    env:
      BEFORE_BUILD_TARGET_WORKSPACE: 'sudo apt-get install -y libboost-all-dev'
      UPSTREAM_WORKSPACE: 'github:SICKAG/sick_safevisionary_base#main'
      ROSDEP_SKIP_KEYS: 'sick_safevisionary_base'
    strategy:
      fail-fast: false
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
